### ISSUE TITLE
Incompatible with Retail Xbox HDD?

### ISSUE THREAD

**Issue by haloman30** [Xenomega/ArchLoader#1]
When I hook up my only Hard Drive (The same one I use on my retail 360) It spits this:
![2014-06-26 03-39-48](https://cloud.githubusercontent.com/assets/7994024/3396415/272e81ec-fd0e-11e3-9999-6cee62357de0.png)

**Comment by Xenomega** [comment]
It is 100% compatible with any hard drive, any motherboard revision or variant of an Xbox 360 development kit. And there is only one Halo 4 network test executable so it's not an issue of version mismatch. It's likely you've modified something on your system that caused this to fail, somehow messed up compilation, or you ran this on the retail Halo 4 game instead of the network test. I suggest making sure optimizations are turned off in the project, and you use an account that never ran the retail Halo 4 game to avoid pollutant data, etc. This has been tested and used by various people in the scene on all flavors of hardware. HDD/hardware details are abstracted away from such applications so they will not pose any issues.

**Comment by haloman30** [comment]
Oh I forgot I even made this lol, the issue I found was due to certain things being enabled/disabled in DashLaunch. Thanks for the help though!

**Comment by Xenomega** [comment]
Ah, okay. Sorry for the late response. Cheers.

**Comment by haloman30** [comment]
Sorry for leaving an issue open for 3 years :stuck_out_tongue:
